### ISSUE TITLE
Support short-circuiting or `isdefined` operator?

### ISSUE THREAD

**Issue by rh389** [silentmatt/expr-eval#119]
Great library. I've just started using it in the context of dynamic forms, where fields should appear subject to some condition on previously set values.

One issue I've come across in this context is variables not being defined when conditions are chained. Say `Q2` appears conditionally on `Q1==1`, and `Q3` appears if `Q1==1 and Q2==1`. Field values are only defined if the field is visible.

`Q1` is always defined but `Q2` is only defined sometimes, so my condition for displaying `Q3` throws an error. In javascript `Q1==1 && Q2==1` would evaluate safely since short-circuiting would prevent the second expression being evaluated. Could we do something similar here, or is there an alternative?

(Another option might be the ability to specify a default value for unbound variables?)

**Comment by silentmatt** [comment]
That's a great idea, thanks. It shouldn't be too hard to implement by compiling `a and b` similarly to `a ? b : false` and `a or b` as `a ? true : b`. I'll work on that when I get a chance.

I also like the idea of an isdefined operator (possible alternative names: exists, defined). One thing I'll need to consider is what happens if the variable exists, but is undefined or null. Would that be true, or false? My initial reaction is leaning towards false, because there's no real support for null or undefined values, and treating those as existing is likely to cause problems. If you have any input feel free to share.
