### ISSUE TITLE
Floating point calculation is not correct.

### ISSUE THREAD

**Issue by sometowngeek** [silentmatt/expr-eval#121]
I ran into an issue with **expr-eval**. It correctly adds integers, but not floating points.

Here is the code I used:

```
function evaluate(expression){
  let solution = parser.evaluate(expression.length > 0 ? expression : '0');

  console.log(expression + " = " + solution);
}
```
----

With the following test cases:

1. 4+3
  a. 4+3 = 7
2. 4+4.1
  a. 4+4.1 = 8.1
3. 4.2+4.1
  a. 4.2+4.1 = 8.3
4. 4.3+4.1
  a. 4.3+4.1 = 8.399999999999999
5. 3.6+3.1
  a. 3.6+3.1 = 6.7
6. 3.6+3.7
  a. 3.6+3.7 = 7.300000000000001
7. 7.894561230.123+1.001
 a. 7894561230.123+1.001 = 7894561231.124001

Test cases 4, 6, and 7 failed.

----

I think the issue lies within your framework. Is it possible that you could fix it? 😃

**Comment by silentmatt** [comment]
That's a limitation of the way JavaScript (and most programming languages) represent floating point numbers. Some base-10 floating point numbers can't be represented exactly, and with some calculations the small errors add up to a large enough error to affect the output.

For display purposes, you could try something like this, which trades off a little bit of precision for nicer results (in most cases):

    console.log(expression + " = " + Number(solution.toPrecision(12)));

I somewhat arbitrarily picked 12 because it will clean up most small answers without losing too much precision. 15 is the practical limit before the rounding errors start showing up all the time.

If you need something that supports arbitrary precision, you could try [math.js](http://mathjs.org/). It has an expression parser similar to mine, but [you can configure it to use BigNumbers](http://mathjs.org/docs/expressions/syntax.html#bignumbers).

**Comment by mixa9269** [comment]
I found this workaround:

```const bignum = num => Math.round(num * 100000000000000) / 100000000000000;

const parser = new Parser();

parser.binaryOps['-'] = (a, b) => bignum(a - b);
parser.binaryOps['+'] = (a, b) => bignum(a + b);

console.log(parser.evaluate('4.3+4.1')); // 8.4
```
