### ISSUE TITLE
Add normal operations

### ISSUE THREAD

**Issue by VictorSnow** [silentmatt/expr-eval#124]
will be perfect to add basic js operations  `||` `&&`

currently has `and` and `or` operator, but still can add theses to be compatible with js expression

**Comment by silentmatt** [comment]
I can see advantages to this, but compatibility with JavaScript expressions isn't really a priority for me since it's intended to be more math-oriented (for example, `^` is exponentiation, not XOR), and I'd prefer not having multiple operators for the same thing. There's also the issue that `||` is being used for string concatenation (borrowed from SQL), and I'm not sure it's worth breaking backward compatibility over.

I'm closing this for now, but I'm open to arguments for keeping it open.

**Comment by Gillardo** [comment]
i would like this, but instead of || and && i would be happy to use keyboards AND and OR, if thats possible
