### ISSUE TITLE
Function if(x, y, z) always evaluates both y and z

### ISSUE THREAD

**Issue by ukrbublik** [silentmatt/expr-eval#142]
I don't know if it's problem, but..
If I use `x ? y : z` only `y` or `z` will be evaluated (depends on condition`x`), which i OK.
But if I use functional form `if(x, y, z)` both params `y` and `z` will be always evaluated before using in `if`.
It's not totally ok if I want to use custom functions as params of `if` and they should not be evaluated unconditionally.

**Comment by silentmatt** [comment]
I'm glad you brought this up, because it's something that's bugged me for awhile, but I haven't made an issue for it. The `if` function is there because it was a quick way to do conditionals before the `x ? y : z` form existed. Now that we have real conditionals, it's really only there for backward compatibility, and definitely isn't ideal because it's inconsistent, and potentially confusing.

One option would be to essentially treat `if(x, y, z)` as a macro and convert it to `x ? y : z` instead of a normal function call. The other option would be removing the function, which is simpler as long as there's not a reason for keeping it around. Either one would be a breaking change requiring a major version update, so backward compatibility isn't really a concern.
