### ISSUE TITLE
how to add my own binaryOps?

### ISSUE THREAD

**Issue by xxShawn** [silentmatt/expr-eval#143]
i want LIKE or NOTLIKE binaryOps.for example 
`a LIKE b`
thank you

**Comment by silentmatt** [comment]
Currently, there's no built-in support for adding custom operators like that. If you want to fork the code and add it though, it's fairly easy when the operator is alphanumeric. Using symbols is slightly more involved because you need to teach the tokenizer to recognize them as operators.

There are basically two steps: Add the operators to the parser, and add functions that implements them to `binaryOps`. Assuming you'd want the precedence to match the comparison operators, that's as easy as adding `'LIKE'` and `'NOTLIKE'` to the `COMPARISON_OPERATORS` array in `src/parser-state.js`.

    var COMPARISON_OPERATORS = ['==', '!=', '<', '<=', '>=', '>', 'in', 'LIKE', 'NOTLIKE'];

Then you would add the implementation functions to the `binaryOps` object in the `Parser` constructor (`src/parser.js`). Any function that takes two arguments and returns a result will work, so it would be something like this:

    // The built-in operators are defined in src/functions.js, but they just need to be visible in src/parser.js
    function likeOperator(a, b) {
      // This is assuming b is a regular expression. Adjust based on what exactly you mean by like/not like
      return new RegExp(b).test(a);
    }
    function notLikeOperator(a, b) {
      return !likeOperator(a, b);
    }

    export function Parser(options) {
      // ...
      this.binaryOps = {
        // ...
        LIKE: likeOperator,
        NOTLIKE: notLikeOperator
      };
      // ...
    }

Hopefully that makes sense. Let me know if you have any questions or issues.

**Comment by NexxLuo** [comment]
Hey, could you tell me how to add a binaryOps with using symbols ?

**Comment by silentmatt** [comment]
@NexxLuo The process would be essentially the same, but you'd also need to update the tokenizer so it recognizes your symbol(s) as a valid token. Exactly how you do that would depend on the symbol you're using (for example, doing something like '++' would need to be handled differently from a brand-new symbol like '$'). The place you'd need to add the logic is the [`TokenStream.prototype.isOperator` method in token-stream.js](https://github.com/silentmatt/expr-eval/blob/b5e3d611c387334f10b36590624a103a6dd7b28d/src/token-stream.js#L375).

**Comment by NexxLuo** [comment]
I get it,thanks very much.
