### ISSUE TITLE
indexOf polyfill overwrites native implementation

### ISSUE THREAD

**Issue by anzeo** [silentmatt/expr-eval#59]
The polyfill introduced by PR https://github.com/silentmatt/expr-eval/pull/3 overwrites the native implementation of indexof *in all browsers*.

Due to the fact this polyfill is suboptimal, this has severe performance issues in larger applications. Please consider removing it (as indexOf is supported in all major browsers and from IE9 onwards) or fix the check to only overwrite the indexOf function if it really isn't present.

**Comment by queequac** [comment]
+1
Since I have to patch the library for other reasons anyway, this was also the very first thing I removed from the lib. ;-)

**Comment by silentmatt** [comment]
This is fixed already in the last couple versions. The current indexOf is a standalone function instead of a property on Array.prototype.

**Comment by queequac** [comment]
Hi Matthew, I know it was changed that way... but that does not affect the performance point and has the same effect as a polyfill (that is: supporting legacy browsers).
The array's built-in indexOf is still faster than a  custom JS implementation - no matter if added to the prototype or implemented in a separate method.

My patch replaces all references with the actual array and its own indexOf.

**Comment by silentmatt** [comment]
I'll probably replace the indexOf function eventually eventually anyway because it's only being used for set membership, but with the array sizes it's running on, the performance impact is going to be pretty minimal if any.

In an artificial benchmark, it's actually running slightly faster than the native function in V8, but it's possible that's due to over-optimization for that specific case. I'm working on some benchmarks, so once that's done, I'll look into it more. My guess is that, for parsing at least, an object property lookup will be faster.
