### ISSUE TITLE
`!true` and `!false`

### ISSUE THREAD

**Issue by eirikb** [silentmatt/expr-eval#60]
Hi

Should `!true` return `false`, and `!false` return `true`?
I noticed in the tests that there is a `not` keyword which does exactly this, but the `!` doesn't seem to work.
E.g.,
```
    // Fails
    it('!true', function () {
      expect(parser.evaluate('!true')).to.equal(false);
    });

    // Fails
    it('!false', function () {
      expect(parser.evaluate('!false')).to.equal(true);
    });

    // Works
    it('not true', function () {
      expect(parser.evaluate('not true')).to.equal(false);
    });

    // Works
    it('not false', function () {
      expect(parser.evaluate('not false')).to.equal(true);
    });
```

**Comment by silentmatt** [comment]
`!` is being used for factorials instead of logical not, which is why that doesn't work. I've considered using the traditional javascript logic operators for consistency, but decided against it. Since factorial is a suffix operator, and not is prefix, it should be possible to support both, so I might consider adding that in the future, but I don't have any plans to at the moment.

For reference, it uses `and` and `or` instead of `&&` and `||` as well (`||` is actually the string concatenation operator, so that `+` is always addition).

**Comment by eirikb** [comment]
That makes a lot of sense, thanks.

Perhaps add `not` to readme?
I see it's mentioned under *Operator Precedence*, but not what it does, so while I had seen `and` and `or` I didn't see `not` until looking at the tests.

**Comment by silentmatt** [comment]
Oh, you're right, just added it to the list.
