### ISSUE TITLE
"Unexpected number" Exception

### ISSUE THREAD

**Issue by ikke09** [silentmatt/expr-eval#73]
I have a Three.js project where i want to calculate the tangential plane for a given function.

In order to do so I create a function as string for the tangential plane. For most cases that works fine, but in some cases the string can not be parsed in a JSFunction.

My function string looks like this:
"-0.7157103444368793*(x-(3.2981185793406347))+(-0.7157103444368793)*(y-(-0.9296815687840398))+0.698397238587069"

My Browser gives me this error:
Uncaught SyntaxError: Unexpected number
    at new Function (<anonymous>)
    at Expression.toJSFunction (parser.js:293)
    at createTangentialPlane (main.js:185)
    at createGraph (main.js:165)
    at <anonymous>:1:1

Can please someone say me whats wrong with my function string? Are the parenthesis wrong?

**Comment by silentmatt** [comment]
Can you show me the code that calls `toJSFunction`? This is working for me:

    var exp = parser.parse('-0.7157103444368793*(x-(3.2981185793406347))+(-0.7157103444368793)*(y-(-0.9296815687840398))+0.698397238587069');
    var f = exp.toJSFunction('x, y');

I don't see anything wrong with your expression, so it's supposed to be working.

**Comment by ikke09** [comment]
Here is my code where i get the exceptions:
```
var x0 = guiElements.X0;
    var y0 = guiElements.Y0;
    var z0 = originalFunction(x0, y0);
    var partialXFunc = Parser.parse(guiElements.PartialX).toJSFunction(["x,y"]);
    var partialYFunc = Parser.parse(guiElements.PartialY).toJSFunction(["x,y"]);
    var ebenenFunctionString = partialXFunc(x0, y0) + "*(x-(" + x0 + "))+(" + partialYFunc(x0, y0) + ")*(y-(" + y0 + "))+" + z0;
    var ebenenFunction = Parser.parse(ebenenFunctionString).toJSFunction(["x,y"]); // Here is where the exception happens

```    

Detailed Information about the code:
My base function, in the case with the error, is sin(x+y). The user types also the partial derivations in to calculate the tangential plane. He can use a mouse click to change the starting point for the tangential plane. And in some cases, for example x0 = -7 and y0 = -3, the calculation breaks.

**Comment by silentmatt** [comment]
I found the problem. There was a bug in the version of the library that you're using that didn't handle negative numbers correctly in some cases and it ends up generating an expression like `y--0.929...`. I would recommend downloading the newest version from https://cdnjs.cloudflare.com/ajax/libs/expr-eval/1.0.0/bundle.min.js (or https://cdnjs.cloudflare.com/ajax/libs/expr-eval/1.0.0/bundle.js for the unminified version). You could also install it or build it from the git repository with npm. The only change you should need to make is to access the Parser class with `exprEval.Parser` instead of just `Parser`.

If you want to stay with the current version, you could also change toJSFunction to remove the call to simplify (which is the source of the bug). So it would look like this:

    toJSFunction: function (param) {
        var f = new Function(param, "with(Parser.values) { return " + this.toString(true) + "; }");
        return f;
    }

I would recommend using the latest version though, since there have been several other bug fixes and improvements since the version you're using.
